global:
  # Reserved for future use
  region: default
  logsLevel: info
  # Uncomment and point to valid URL to enable tracing
  # otlExporter: http://jaeger:14268/api/traces

# EdgePort Service defaults
edgeport:
  # Set a password for the JAIN SIP security context
  # The password will be securely stored in a k8s secret
  pkcs12Password: changeme
  # External addresses. Required for edgeport to work
  externalAddrs: []
  # By default, it loads the local networks as reported by the operating system
  # Use this in combination with externalAddrs for correct address advertisement
  # localnets: []
  # Acceptable SIP methods
  methods:
    - REGISTER
    - MESSAGE
    - INVITE
    - ACK
    - BYE
    - CANCEL
  # Uncomment to enable experimental support for the HEP protocol
  # heplifyOptions: "-hs homerserver:9060"
  # Reserved for future use
  unknownMethodAction: Discard
  # EdgePort image configuration
  image:
    # EdgePort image repository
    repository: fonoster/routr-edgeport
    # EdgePort image tag (immutable tags are recommended)
      # Uncomment to overwrite Chart.appVersion
    # tag: latest
    # EdgePort image pull policy default to IfNotPresent
    pullPolicy: IfNotPresent
  # Pod annotations
  podAnnotations: {}
  # Service annotations for TCP
  serviceAnnotationsTCP: {}
  # Service annotations for UDP
  serviceAnnotationsUDP: {}
  # The type for the service (TCP)
  serviceTypeTCP: NodePort
  # The type for the service (UDP)
  serviceTypeUDP: NodePort
  # Denotes if this Service desires to route external traffic to node-local or cluster-wide endpoints (UDP)
  externalTrafficPolicyUDP: Cluster
  # Denotes if this Service desires to route external traffic to node-local or cluster-wide endpoints (TCP)
  externalTrafficPolicyTCP: Cluster
  # Enable health checks for the UDP service
  udpHealthCheck: false
  # Security context for EdgePort
  transport:
    # TCP transport configuration
    tcp:
      # Whether TCP transport is enabled
      enabled: false
      # TCP port
      port: 5060
    # UDP transport configuration  
    udp:
      # Whether UDP transport is enabled
      enabled: true
      # UDP port
      port: 5060
    # TLS transport configuration  
    tls:
      # Whether TLS transport is enabled
      enabled: false
      # TLS port
      port: 5061
    # WebSocket transport configuration
    ws:
      # Whether WebSocket transport is enabled
      enabled: false
      # WebSocket port
      port: 5062
    # Secure WebSocket transport configuration
    wss:
      # Whether Secure WebSocket transport is enabled
      enabled: false
      # Secure WebSocket port
      port: 5063
  # Maximum number of replicas
  replicas: 2
  # Minimum time for the pod to be ready before accepting traffic
  minReadySeconds: 10
  # Maximum time for the pod to be ready before being killed
  terminationGracePeriodSeconds: 10
  # Security context for EdgePort
  securityContext:
    # Running as a non-root user
    runAsUser: 1000
    # Running as a non-root group
    runAsGroup: 3000
    # File system group
    fsGroup: 2000
    # By default, no privilege escalation is allowed
    allowPrivilegeEscalation: false
  # Liveness probe configuration
  livenessProbe:
    # Initial delay in seconds before starting the liveness probe
    initialDelaySeconds: 10
    # Period between liveness probes
    periodSeconds: 5
    # Number of successes required to be considered healthy 
    successThreshold: 1
    # Number of failures required to be considered unhealthy
    failureThreshold: 2
    # Timeout for liveness probe
    timeoutSeconds: 1
  # Resource limits and requests
  resources:
    # Resource limits
    limits: {}
    # Resource requests
    requests: {}

# Dispatcher Service defaults
dispatcher:
  processors:
      # The name of the processor
    - ref: connect-processor
      serviceName: routr-connect
      # The function used to match requests with this processor
      matchFunc: "req => true"
      # Acceptable SIP Methods
      methods: ["REGISTER", "MESSAGE", "INVITE", "ACK", "BYE", "CANCEL"]
  middlewares: []
  image:
    # Dispatcher image repository
    repository: fonoster/routr-dispatcher
    # Dispatcher image tag (immutable tags are recommended)
    # Uncomment to overwrite Chart.appVersion
    # tag: latest
    # Dispatcher image pull policy default to IfNotPresent
    pullPolicy: IfNotPresent
  # Pod annotations
  podAnnotations: {}
  # Service annotations
  serviceAnnotations: {}
  # Security context for Dispatcher
  securityContext:
    # Running as a non-root user
    runAsUser: 1000
    # Running as non-root group
    runAsGroup: 3000
    # File system group
    fsGroup: 2000
    # By default, no privilege escalation is allowed
    allowPrivilegeEscalation: false
  # Liveness probe configuration
  livenessProbe:
    # Initial delay in seconds before starting the liveness probe
    initialDelaySeconds: 5
    # Period between liveness probes
    periodSeconds: 5
    # Number of successes required to be considered healthy
    successThreshold: 1
    # Number of failures required to be considered unhealthy
    failureThreshold: 2
    # Timeout in seconds for liveness probe
    timeoutSeconds: 1
  # Resource limits and requests
  resources:
    # Resource limits
    limits: {}
    # Resource requests
    requests: {}
  # Autoscaling configuration
  autoscaling:
    # Minimum number of replicas
    minReplicas: 1
    # Maximum number of replicas
    maxReplicas: 10
    # Target CPU utilization percentage
    targetCPUUtilizationPercentage: 50
    # Target memory utilization percentage
    targetMemoryUtilizationPercentage: 70

# Location Service defaults
location:
  # Region for Location service (reserved for future use)
  region: default
  # Location cache configuration
  cache:
    # Location cache provider
    provider: redis
    # Location cache parameters (see configmap for defaults)
    parameters: ""
  # Location image configuration
  image:
    # Location image repository
    repository: fonoster/routr-location
    # Location image tag (immutable tags are recommended)
    # Uncomment to overwrite Chart.appVersion
    # tag: latest
    # Location image pull policy default to IfNotPresent
    pullPolicy: IfNotPresent
  # Pod annotations  
  podAnnotations: {}
  # Service annotations
  serviceAnnotations: {}
  # Security context for Location
  securityContext:
    # Running as a non-root user
    runAsUser: 1000
    # Running as a non-root group
    runAsGroup: 3000
    # File system group
    fsGroup: 2000
    # By default, no privilege escalation is allowed
    allowPrivilegeEscalation: false
  # Liveness probe configuration
  livenessProbe:
    # Initial delay in seconds before starting the liveness probe
    initialDelaySeconds: 5
    # Period between liveness probes
    periodSeconds: 5
    # Number of successes required to be considered healthy
    successThreshold: 1
    # Number of failures required to be considered unhealthy
    failureThreshold: 2
    # Timeout in seconds for liveness probe
    timeoutSeconds: 1
  # Resource limits and requests
  resources:
    # Resource limits
    limits: {}
    # Resource requests
    requests: {}
  # Autoscaling configuration
  autoscaling:
    # Minimum number of replicas
    minReplicas: 1
    # Maximum number of replicas
    maxReplicas: 10
    # Target CPU utilization percentage
    targetCPUUtilizationPercentage: 50
    # Target memory utilization percentage
    targetMemoryUtilizationPercentage: 70

# APIServer Service defaults
apiserver:
  # Uncomment the next line if you want to point to an external postgresql db
  # databaseUrl: postgresql://routr:changeme@dbserver:5432/routr?schema=public
  # Set to false if you want to disable TLS for the APIServer (Not recommended)
  tlsOn: true
  # When set to true the APIServer will require client certificates
  verifyClientCert: false
  # Uncomment the next line if you want to enable field level encryption
  # Create a new encryption key with cloack (https://cloack.47ng.com)
  # cloakEncryptionKey: k1.aesgcm256...
  # APIServer image configuration
  image:
    # APIServer image repository
    repository: fonoster/routr-pgdata
    # APIServer image tag (immutable tags are recommended)
    # Uncomment to overwrite Chart.appVersion
    # tag: latest
    # APIServer image pull policy default to IfNotPresent
    pullPolicy: IfNotPresent
  migrations:
    enabled: true
    image:
      # APIServer migrations image repository
      repository: fonoster/routr-pgdata-migrations
      # APIServer migrations image tag (immutable tags are recommended)
      # Uncomment to overwrite Chart.appVersion
      # tag: latest
      # APIServer image pull policy default to IfNotPresent
      pullPolicy: IfNotPresent
    resources:
      # Resource limits
      limits: {}
      # Resource requests
      requests: {}
  # Pod annotations
  podAnnotations: {}
  # Service annotations
  serviceAnnotations: {}
  # Security context for APIServer    
  securityContext:
    # Running as a non-root user
    runAsUser: 1000
    # Running as a non-root group
    runAsGroup: 3000
    # File system group
    fsGroup: 2000
    # By default, no privilege escalation is allowed
    allowPrivilegeEscalation: false
  # Liveness probe configuration
  livenessProbe:
    # Initial delay in seconds before starting the liveness probe
    initialDelaySeconds: 5
    # Period between liveness probes
    periodSeconds: 5
    # Number of successes required to be considered healthy
    successThreshold: 1
    # Number of failures required to be considered unhealthy
    failureThreshold: 2
    # Timeout in seconds for liveness probe
    timeoutSeconds: 4
  # Resource limits and requests
  resources:
    # Resource limits
    limits: {}
    # Resource requests
    requests: {}
  # Autoscaling configuration  
  autoscaling:
    # Minimum number of replicas
    minReplicas: 1
    # Maximum number of replicas
    maxReplicas: 10
    # Target CPU utilization percentage
    targetCPUUtilizationPercentage: 50
    # Target memory utilization percentage
    targetMemoryUtilizationPercentage: 70

# Connect Service defaults
connect:
  # Connect image configuration
  image:
    # Connect image repository
    repository: fonoster/routr-connect
    # Connect image tag (immutable tags are recommended)
    # Uncomment to overwrite Chart.appVersion
    # tag: latest
    # Connect image pull policy default to IfNotPresent
    pullPolicy: IfNotPresent
  # Pod annotations
  podAnnotations: {}
  # Service annotations
  serviceAnnotations: {}
  # Security context for Connect    
  securityContext:
    # Running as non-root user
    runAsUser: 1000
    # Running as non-root group
    runAsGroup: 3000
    # File system group
    fsGroup: 2000
    # By default, no privilege escalation is allowed
    allowPrivilegeEscalation: false
  # Liveness probe configuration
  livenessProbe:
    # Initial delay in seconds before starting the liveness probe
    initialDelaySeconds: 5
    # Period between liveness probes
    periodSeconds: 5
    # Number of successes required to be considered healthy
    successThreshold: 1
    # Number of failures required to be considered unhealthy
    failureThreshold: 2
    # Timeout in seconds for liveness probe
    timeoutSeconds: 1
  # Resource limits and requests
  resources:
    # Resource limits
    limits: {}
    # Resource requests
    requests: {}
  # Autoscaling configuration
  autoscaling:
    # Minimum number of replicas
    minReplicas: 1
    # Maximum number of replicas
    maxReplicas: 10
    # Target CPU utilization percentage
    targetCPUUtilizationPercentage: 50
    # Target memory utilization percentage
    targetMemoryUtilizationPercentage: 70

# Registry Service defaults
registry:
  # Registry image configuration
  registerInterval: 20
  # Cache configuration
  cache:
    # Cache provider. Default to memory
    provider: redis
    # Cache parameters. Default to empty string
    parameters: ""
  # Registry image configuration
  methods:
    - INVITE
    - MESSAGE
  # Registry image configuration
  image:
    # Registry image repository
    repository: fonoster/routr-registry
    # Registry image tag (immutable tags are recommended)
    # Uncomment to overwrite Chart.appVersion
    # tag: latest
    # Registry image pull policy default to IfNotPresent
    pullPolicy: IfNotPresent
  # Pod annotations
  podAnnotations: {}
  # Service annotations
  serviceAnnotations: {}
  # Security context for Registry
  securityContext:
    # Running as a non-root user
    runAsUser: 1000
    # Running as non-root group
    runAsGroup: 3000
    # File system group
    fsGroup: 2000
    # By default, no privilege escalation is allowed
    allowPrivilegeEscalation: false
  # Liveness probe configuration
  livenessProbe:
    # Initial delay in seconds before starting the liveness probe
    initialDelaySeconds: 5
    # Period between liveness probes
    periodSeconds: 5
    # Number of successes required to be considered healthy
    successThreshold: 1
    # Number of failures required to be considered unhealthy
    failureThreshold: 2
    # Timeout in seconds for liveness probe
    timeoutSeconds: 2
  # Resource limits and requests
  resources:
    # Resource limits
    limits: {}
    # Resource requests
    requests: {}
  # Autoscaling configuration
  autoscaling:
    # Minimum number of replicas
    minReplicas: 1
    # Maximum number of replicas
    maxReplicas: 10
    # Target CPU utilization percentage
    targetCPUUtilizationPercentage: 50
    # Target memory utilization percentage
    targetMemoryUtilizationPercentage: 70

# Requester Service defaults
requester:
  # Requester image configuration
  image:
    # Requester image repository
    repository: fonoster/routr-requester
    # Requester image tag (immutable tags are recommended)
    # Uncomment to overwrite Chart.appVersion
    # tag: latest
    # Requester image pull policy default to IfNotPresent
    pullPolicy: IfNotPresent
  # Pod annotations
  podAnnotations: {}
  # Service annotations
  serviceAnnotations: {}
  # Security context for Requester
  securityContext:
    # Running as a non-root user
    runAsUser: 1000
    # Running as a non-root group
    runAsGroup: 3000
    # File system group
    fsGroup: 2000
    # By default, no privilege escalation is allowed
    allowPrivilegeEscalation: false
  # Liveness probe configuration
  livenessProbe:
    # Initial delay in seconds before starting the liveness probe
    initialDelaySeconds: 10
    # Period between liveness probes
    periodSeconds: 5
    # Number of successes required to be considered healthy
    successThreshold: 1
    # Number of failures required to be considered unhealthy
    failureThreshold: 2
    # Timeout in seconds for liveness probe
    timeoutSeconds: 2
  # Resource limits and requests 
  resources:
    # Resource limits
    limits: {}
    # Resource requests
    requests: {}
  # Autoscaling configuration
  autoscaling:
    # Minimum number of replicas
    minReplicas: 1
    # Maximum number of replicas
    maxReplicas: 10
    # Target CPU utilization percentage
    targetCPUUtilizationPercentage: 50
    # Target memory utilization percentage
    targetMemoryUtilizationPercentage: 70

# RTPRelay Service defaults
rtprelay:
  enabled: false
  # RTPEngine host
  rtpeHost: ""
  # RTPEngine port
  rtpePort: 22222
  # RTPRelay image configuration
  image:
    # RTPRelay image repository
    repository: fonoster/routr-rtprelay
    # RTPRelay image tag (immutable tags are recommended)
    # Uncomment to overwrite Chart.appVersion
    # tag: latest
    # RTPRelay image pull policy default to IfNotPresent
    pullPolicy: IfNotPresent
  # Pod annotations
  podAnnotations: {}
  # Service annotations
  serviceAnnotations: {}
  # Security context for RTPRelay
  securityContext:
    # Running as a non-root user
    runAsUser: 1000
    # Running as a non-root group
    runAsGroup: 3000
    # File system group
    fsGroup: 2000
    # By default, no privilege escalation is allowed
    allowPrivilegeEscalation: false
  # Liveness probe configuration
  livenessProbe:
    # Initial delay in seconds before starting the liveness probe
    initialDelaySeconds: 5
    # Period between liveness probes
    periodSeconds: 5
    # Number of successes required to be considered healthy
    successThreshold: 1
    # Number of failures required to be considered unhealthy
    failureThreshold: 2
    # Timeout in seconds for liveness probe
    timeoutSeconds: 4
  # Resource limits and requests
  resources:
    # Resource limits
    limits: {}
    # Resource requests
    requests: {}
  # Autoscaling configuration
  autoscaling:
    # Minimum number of replicas
    minReplicas: 1
    # Maximum number of replicas
    maxReplicas: 10
    # Target CPU utilization percentage
    targetCPUUtilizationPercentage: 50
    # Target memory utilization percentage
    targetMemoryUtilizationPercentage: 70

# Postgresql Service defaults 
postgresql:
  # Whether to enable PostgreSQL
  enabled: true
  auth:
    # Initial username for the database
    username: routr
    # Initial password for the database
    password: changeme

# Redis Service defaults
redis:
  # Whether to enable Redis
  enabled: true
  architecture: standalone
  auth:
    enabled: false
